### PR TITLE
Travis runs on all specified python versions

### LINKED ISSUE #2: Configure Travis/Jenkins for automated testing

### PR DESCRIPTION
**Pull request by abinashmeher999**
fixes #2

### CODE REVIEW

**Review by djr-jsr — CHANGES_REQUESTED** [review]
IMO, remove 3.3 and 3.4 also, keep 3.5 and nightly.

**Comment by abinashmeher999** [comment]
It was a bold step to remove 2.7. Wouldn't removing 3.3 and 3.4 be a little extreme? And do we really need to test against nightly? It is a development branch.

**Comment by djr-jsr** [comment]
I was suggesting nightly because since its a future development branch, our project should be compatible with it. 😕

**Comment by abinashmeher999** [comment]
Ok. I will add nightly.

**Review by djr-jsr — APPROVED** [review]

**Pull request merged**
